name: CI

on: [push, pull_request]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-20.04

    steps:
      # Initialization
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: docker run --rm -v $(pwd):/app node:18-bookworm 'cd app; npm ci'
      - name: Copy configuration
        run: cp config.json.example config.json

      # # Run linter
      # - name: Lint
      #   run: npm run lint

      # Create Chrome artifacts
      - name: Create Chrome artifacts
        run: docker run --rm -v $(pwd):/app node:18-bookworm 'cd app; npm run build:chrome'
      - uses: actions/upload-artifact@v3
        with:
          name: ChromeExtension
          path: dist
      - run: mkdir ./builds
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/ChromeExtension.zip ./dist
